"""Data models and state definitions for the chatbot agents."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, TypedDict

import pandas as pd


class AgentRole(str, Enum):
    """Enumeration of agent roles in the workflow."""
    PLANNER = "planner"
    SQL_GENERATOR = "sql_generator"
    VALIDATOR = "validator"
    WRITER = "writer"


@dataclass
class QueryPlan:
    """Plan generated by the planner agent with natural language instructions."""
    user_intent: str  # What the user is truly trying to understand
    assumptions: list[str]  # Assumptions made about the question
    instructions: str  # Detailed natural language instructions for SQL generator
    output_requirements: list[str]  # Specific data points that must be in the answer
    sorting_preference: str  # How results should be ordered
    limit_preference: str  # Whether to limit results
    complexity: str  # low, medium, high


@dataclass
class SQLResult:
    """Result from SQL query execution."""
    query: str
    success: bool
    data: pd.DataFrame | None = None
    error: str | None = None
    row_count: int = 0
    reasoning: str = ""  # SQL generator's reasoning for the query

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "query": self.query,
            "success": self.success,
            "data": self.data.to_dict(orient="records") if self.data is not None else None,
            "error": self.error,
            "row_count": self.row_count,
            "reasoning": self.reasoning,
        }


@dataclass
class ValidationResult:
    """Result from the validation agent."""
    is_valid: bool
    confidence: float  # 0.0 to 1.0
    issues: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    reasoning: str = ""


class AgentState(TypedDict, total=False):
    """
    State passed between agents in the LangGraph workflow.

    This TypedDict defines all possible state fields that can be
    passed between agents during the workflow execution.
    """
    # User input
    user_query: str

    # Database schema context
    schema_context: str

    # Planner agent output (natural language instructions)
    query_plan: dict[str, Any]

    # SQL generator output
    sql_query: str
    sql_reasoning: str  # SQL generator's reasoning
    sql_result: dict[str, Any]

    # Validation agent output
    validation_result: dict[str, Any]

    # Writer agent output
    final_response: str

    # Workflow control
    retry_count: int
    error_message: str
    should_retry: bool

    # Conversation history for context
    messages: list[dict[str, str]]
